spring:
  # 配置数据源
  datasource:
    ds1:
#      url: jdbc:mysql://localhost:3306/demo1?useUnicode=true&characterEncoding=utf8&useSSL=true
      url: jdbc:mysql://172.16.1.114:3306/sia9?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Hubin123
      driver-class-name: com.mysql.jdbc.Driver

# 配置web端口
server:
  port: 10000

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  # mybatis全局配置文件位置
  config-location: classpath:/mybatis/config/mybatis-config.xml

