spring:
  # 配置数据源
  datasource:
    old:
      url: jdbc:mysql://localhost:3306/koala_crm?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    new:
      url: jdbc:mysql://47.103.14.178:3306/koala_crm?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 1qaz@WSX
      driver-class-name: com.mysql.jdbc.Driver

# 配置web端口
server:
  port: 10000
  servlet:
    context-path: /mybatis/xml

mybatis:
  mapper-locations: classpath:/mybatis/mapper/old/*.xml
  # mybatis全局配置文件位置
  config-location: classpath:/mybatis/config/mybatis-config.xml


logging:
  level:
    # 只打印sql语句
    com.example.demo.dao: debug


