POST http://localhost:10000/mybatis/xml/coupon/template/add
Content-Type: application/json

{
  "couponName":"测试票券1",
  "receieveStart":"2020-01-01 00:00:00",
  "receieveEnd":"2020-02-01 23:59:59"
}

###

GET http://localhost:10000/mybatis/xml/coupon/template/list
Content-Type: application/json




